# Autogenerated wrapper script for Polymers_jll for aarch64-apple-darwin
export libpolymers

JLLWrappers.@generate_wrapper_header("Polymers")
JLLWrappers.@declare_library_product(libpolymers, "@rpath/libpolymers.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libpolymers,
        "lib/libpolymers.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
