# Autogenerated wrapper script for Polymers_jll for armv6l-linux-gnueabihf
export libpolymers

JLLWrappers.@generate_wrapper_header("Polymers")
JLLWrappers.@declare_library_product(libpolymers, "libpolymers.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libpolymers,
        "lib/libpolymers.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
