# Autogenerated wrapper script for Polymers_jll for x86_64-w64-mingw32
export libpolymers

JLLWrappers.@generate_wrapper_header("Polymers")
JLLWrappers.@declare_library_product(libpolymers, "libpolymers.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libpolymers,
        "bin\\libpolymers.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
